allowed_functions:
  - name: SomeFunc
    classes:
      - pkg
    return_types: [bool]
    parameters:
      - string
  - name: OtherFunc
    classes:
      - pkg
    return_types: [ bool ]
    parameters:
      - string
  - name: CompletelyUnrelated
    classes:
      - receiver
