// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0
package main

const startComponentList = `# Start Collector components list`
const endComponentList = `# End Collector components list`
const startCodeownersComponentList = `# Start components list`
const endCodeownersComponentList = `# End components list`
const startCodeownersUnmaintainedList = `# Start unmaintained components list`
const endCodeownersUnmaintainedList = `# End unmaintained components list`
const startDistributionList = `# Start distribution list`
const endDistributionList = `# End distribution list`
const allowListDeprecatedListHeader = "## DEPRECATED components\n"
const allowListUnmaintainedListHeader = "\n## UNMAINTAINED components\n"
const unmaintainedStatus = "unmaintained"
const deprecatedStatus = "deprecated"

const allowlistHeader = `# Code generated by githubgen. DO NOT EDIT.
#####################################################
#
# List of components
# waiting on owners to be assigned
#
#####################################################
#
# Learn about CODEOWNERS file format:
#  https://help.github.com/en/articles/about-code-owners
#

## 
# NOTE: New components MUST have one or more codeowners. Add codeowners to the component metadata.yaml and run make gengithub
##

`
