// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0
package main

const startComponentList = `# Start Collector components list`
const endComponentList = `# End Collector components list`
const deprecatedListHeader = "## DEPRECATED components\n"
const unmaintainedListHeader = "\n## UNMAINTAINED components\n"

const allowlistHeader = `# Code generated by githubgen. DO NOT EDIT.
#####################################################
#
# List of components in OpenTelemetry Collector Contrib
# waiting on owners to be assigned
#
#####################################################
#
# Learn about membership in OpenTelemetry community:
#  https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md
#
#
# Learn about CODEOWNERS file format:
#  https://help.github.com/en/articles/about-code-owners
#

## 
# NOTE: New components MUST have one or more codeowners. Add codeowners to the component metadata.yaml and run make gengithub
##

## COMMON & SHARED components
internal/common

`

const unmaintainedHeader = `

## UNMAINTAINED components
#####################################################
#

`

const codeownersHeader = `# Code generated by githubgen. DO NOT EDIT.
#####################################################
#
# List of codeowners for %s
#
#####################################################
#
# Learn about membership in OpenTelemetry community:
# https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md
#
#
# Learn about CODEOWNERS file format:
# https://help.github.com/en/articles/about-code-owners
#

* %s
`

const distributionCodeownersHeader = `
#####################################################
#
# List of distribution maintainers for %s
#
#####################################################
`
