// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0
package main

const startComponentList = `# Start Collector components list`
const endComponentList = `# End Collector components list`
const deprecatedListHeader = "## DEPRECATED components\n"
const unmaintainedListHeader = "\n## UNMAINTAINED components\n"
const unmaintainedStatus = "unmaintained"

const allowlistHeader = `# Code generated by githubgen. DO NOT EDIT.
#####################################################
#
# List of components
# waiting on owners to be assigned
#
#####################################################
#
# Learn about CODEOWNERS file format:
#  https://help.github.com/en/articles/about-code-owners
#

## 
# NOTE: New components MUST have one or more codeowners. Add codeowners to the component metadata.yaml and run make gengithub
##

## COMMON & SHARED components
internal/common

`

const unmaintainedHeader = `
#####################################################
#
## UNMAINTAINED components
#
#####################################################
`

const codeownersHeader = `# Code generated by githubgen. DO NOT EDIT.
#####################################################
#
# List of codeowners
#
#####################################################
#
# Learn about CODEOWNERS file format:
# https://help.github.com/en/articles/about-code-owners
#

* %s
`

const distributionCodeownersHeader = `
#####################################################
#
# List of distribution maintainers
#
#####################################################
`
