name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug!
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which tool or component is affected?
      multiple: true
      options:
        - checkapi
        - checkfile
        - chloggen
        - crosslink
        - dbotconf
        - githubgen
        - gotmpl
        - internal
        - issuegenerator
        - multimod
        - semconvgen
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
