name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug!
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which tool or component is affected?
      multiple: true
      options:
        - checkapi
        - checkfile
        - chloggen
        - crosslink
        - dbotconf
        - githubgen
        - gotmpl
        - internal
        - issuegenerator
        - multimod
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
