name: Enhancement
description: Suggest an enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an enhancement!
  - type: dropdown
    id: component
    attributes:
      label: Component(s)
      description: Which tool(s) or component(s) are related? (Select all that apply)
      multiple: true
      options:
        - checkapi
        - checkfile
        - chloggen
        - crosslink
        - dbotconf
        - githubgen
        - gotmpl
        - internal
        - issuegenerator
        - multimod
    validations:
      required: false
  - type: textarea
    id: proposal
    attributes:
      label: Enhancement Proposal
      description: Describe your suggestion.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this enhancement?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
