// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package internal

import (
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"golang.org/x/mod/modfile"
	"gopkg.in/yaml.v3"
)

const header = "# File generated by dbotconf; DO NOT EDIT."

// buildConfig constructs a dependabotConfig for all modules in the repo.
func buildConfig(root string, mods []*modfile.File) (*dependabotConfig, error) {
	c := &dependabotConfig{
		Version: version2,
		Updates: []update{{
			PackageEcosystem: ghPkgEco,
			Directory:        "/",
			Labels:           labels,
			Schedule:         weeklySchedule,
		}},
	}
	for _, m := range mods {
		local, err := localPath(root, m)
		if err != nil {
			return nil, err
		}

		c.Updates = append(c.Updates, update{
			PackageEcosystem: gomodPkgEco,
			Directory:        local,
			Labels:           labels,
			Schedule:         weeklySchedule,
		})
	}
	return c, nil
}

var output io.Writer = os.Stdout

// runGenerate outputs a generated dependabot configuration for all Go modules
// contained in the repository.
func runGenerate(*cobra.Command, []string) error {
	root, mods, err := allMods()
	if err != nil {
		return err
	}

	c, err := buildConfig(root, mods)
	if err != nil {
		return err
	}

	fmt.Fprintln(output, header)
	return yaml.NewEncoder(output).Encode(c)
}
